
title: Online appendix of the "Innovative financial design using encryption" outline
description: An interactive tutorial on replacing the trusted third parties through homomorphic encryption, auctions without auctioneers case¶"
include:
  - index2.md
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-cayman
google_analytics: UA-175064932-2 
